title: Kaden Tang
logo: assets\img\kaden_tang_profile.png
theme: jekyll-theme-minimal
description: Hi I'm Kaden, a sophomore at UC Berkeley studying Applied Math! Some of my interests include EdTech and knowledge representation. Here's a collection of my favorite projects that I've built.
