title: Kaden Tang
logo: assets/img/pfp.png
theme: jekyll-theme-minimal
description: Hi I'm Kaden, a sophomore at UC Berkeley studying Applied Math! Some of my passions include EdTech, playing soccer, and traveling the world. Here's a collection of my favorite AI projects that I've built.
